### ISSUE TITLE
error leap upgrade

### ISSUE THREAD

**Issue by agungsaputro** [oamg/leapp-repository#1051]
i want to upgrade centos 7 to almalinux but i got an error
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/dnfpackagedownload/actor.py", line 51, in process
    xfs_info=xfs_info, storage_info=storage_info, plugin_info=plugin_info, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 385, in perform_rpm_download
    test=True, on_aws=on_aws
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/libraries/dnfplugin.py", line 219, in _transaction
    e.stdout = e.stdout.encode('utf-8', 'xmlcharrefreplace')
AttributeError: can't set attribute
```
I know this is an old bug but it's been ignored, can anyone help me?

**Comment by pirat89** [comment]
@agungsaputro Hi \o I will just correct you: the bug has not been ignored as the bug does not exist in this project, so we cannot fix it nor ignore it, as described here: https://github.com/oamg/leapp-repository/issues/1016#issuecomment-1405227891. This change has been introduced in the Elevate project only, so it can be addressed there only.

We would like to remind that contributions in upstream projects are welcomed, so if someone opens a PR for the generic solution into the upstream project, we will be happy. In this case, the correct solution here ould be from my point of view a fix in the framework / stdlib, where it can be resolved for all calls - instead of fixing the output just for a particular call.
