### ISSUE TITLE
CentOS 7,9 to Almalinux: missing named-user-options.conf

### ISSUE THREAD

**Issue by cooldark** [oamg/leapp-repository#1058]
**Actual behavior**
When starting the "leapp preupgrade" check on a centos 7 machine it breaks with the error:

```
...        Actor parsing BIND configuration and checking for known issues in it.
Process Process-423:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/actor.py", line 32, in process
    facts = iscmodel.get_facts('/etc/named.conf')
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/libraries/iscmodel.py", line 76, in get_facts
    parser = isccfg.IscConfigParser(path)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 407, in __init__
    self.load_config(config)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 949, in load_config
    self.load_included_files()
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 935, in load_included_files
    self.on_include_error(ConfigParseError(e, include))
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 914, in on_include_error
    raise e
ConfigParseError: Cannot open the configuration file "/etc/named-user-options.conf": [Errno 2] No such file or directory: '/etc/named-user-options.conf'; included from "/etc/named-user-options.conf"
```

**To Reproduce**
Steps to reproduce the behavior

probably an individual error

**Expected behavior**
Ignoring the missing file or in case it is empty.

**System information (please complete the following information):**

- CentOS Linux release 7.9.2009 (Core)
- Linux  3.10.0-1160.88.1.el7.x86_64 

```

Attach (or provide link to) log files if applicable (optional - may contain confidential information):

****

**Additional context**

I tried a simple touch on that file but an empty file produces still error message.

**Comment by pirat89** [comment]
@cooldark  Hi \o thank for the report. I've checked the code and to me it seems as invalid system configuration. The code is not trying to access such a file directly, so somewhere in the bind configuration you have present `include /etc/named-user-options.conf` incorrectly even when the file does not exist. Also checking on CentOS 7.9, I cannot find anything asking / providing the file. In this case, I would consider it as a problem of the system configuration that should be fixed. @pemensik wdyt?

**Comment by cooldark** [comment]
Hi [pirat89](https://github.com/pirat89),
thanks for the quick response. I did a check on my side and yes, there is an include which probably is done by Plesk which is installed on the server. So uncommenting/deleting the include would be an idea?

```
// -- THE FOLLOWING LINES WERE GENERATED BY PLESK. IF YOU MODIFY THEM, THEY WILL BE OVERWRITTEN WHEN THESE SETTINGS ARE MANAGED IN PLESK UI. --
options {
        include "/etc/named-user-options.conf";
        allow-recursion {
                localnets;
        };
        directory "/var";
        pid-file "/var/run/named/named.pid";
};

key "rndc-key" {
        algorithm hmac-md5;
        secret "GDVUTqEZyUTTT0dIAfeNBA==";
};

controls {
        inet 127.0.0.1 port 953
        allow { 127.0.0.1; } keys { "rndc-key"; };
};

zone "." {
        type hint;
        file "named.root";
};

zone "0.0.127.IN-ADDR.ARPA" {
        type master;
        file "localhost.rev";
};
// -- END OF LINES GENERATED BY PLESK. --

```

**Comment by pirat89** [comment]
yes, the service is broken:
```
[root@localhost ~]# systemctl status named
● named.service - Berkeley Internet Name Domain (DNS)
   Loaded: loaded (/usr/lib/systemd/system/named.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-03-13 16:44:20 CET; 6s ago
  Process: 15009 ExecStartPre=/bin/bash -c if [ ! "$DISABLE_ZONE_CHECKING" == "yes" ]; then /usr/sbin/named-checkconf -z "$NAMEDCONF"; else echo "Checking of zone files is disabled"; fi (code=exited, status=1/FAILURE)

Mar 13 16:44:20 localhost.localdomain systemd[1]: Starting Berkeley Internet Name Domain (DNS)...
Mar 13 16:44:20 localhost.localdomain bash[15009]: /etc/named.conf:61: open: /etc/mywhateverfile.conf: file not found
Mar 13 16:44:20 localhost.localdomain systemd[1]: named.service: control process exited, code=exited status=1
Mar 13 16:44:20 localhost.localdomain systemd[1]: Failed to start Berkeley Internet Name Domain (DNS).
Mar 13 16:44:20 localhost.localdomain systemd[1]: Unit named.service entered failed state.
Mar 13 16:44:20 localhost.localdomain systemd[1]: named.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by pemensik** [comment]
Also I would suggest placing included files into */etc/named* folder. There they get correct SELinux labels and will work also from *named-chroot.service*. But I just guess SELinux is disabled, because it would not work from directory */var*.

**Comment by cooldark** [comment]
Thanks for the hints, re-created the secret.

As mentioned in the beginning, touching to create an empty file does not help. Error on leapp pre-upgrade :

```
====> * check_bind
        Actor parsing BIND configuration and checking for known issues in it.
Process Process-423:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/actor.py", line 32, in process
    facts = iscmodel.get_facts('/etc/named.conf')
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkbind/libraries/iscmodel.py", line 81, in get_facts
    parser.walk(cfg.root_section(), find_calls, state)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 879, in walk
    for statement in it:
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 223, in __next__
    statement = next(self.iter)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 181, in __next__
    val = self.parser.find_next_key(cfg, index, self.section.end)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/isccfg.py", line 689, in find_next_key
    while istr[index] in self.CHAR_KEYWORD and index < end_index:
IndexError: string index out of range
```

**Comment by pemensik** [comment]
does the configuration before update pass named-checkconf command?

**Comment by striderxfossility** [comment]
i have the same issue, the excact same, cant figure out what to do.

**Comment by pirat89** [comment]
@striderxfossility well, for example drop the `include` directive for the missing / empty files from the main configuration or correct the BIND configuration as per above comments it's obviously broken already. another option is to uninstall it if you do not use it and do not plan to fix it.

**Comment by pirat89** [comment]
As this seems to be issue of incorrect configuration of bind on the system (per discussion above) and we are slowly ending development for EL7 systems, I am closing this ticket.

**Comment by ericmulder1980** [comment]
For anyone using Plesk and reaching this issue. On Plesk the names-user-options.conf is not located in the /etc directory but in the /var/named/chroot/etc/ directory.

Creating the symlink below will fix that issue.

ln -s /var/named/chroot/etc/named-user-options.conf /etc/named-user-options.conf

Credits: https://talk.plesk.com/threads/named-bind-max-cache-size.373672/#post-944465
