### ISSUE TITLE
leapp preupgrade  fails with python error

### ISSUE THREAD

**Issue by tuxmaster5000** [oamg/leapp-repository#1065]
**Actual behavior**
When I try to convert an CentOS 7.9 to Rocky 8, the preupgrade check fails with an python error

**To Reproduce**
call leapp preupgrade

**Expected behavior**
That the tool will present an list of errors or none, when all will be fine

**System information (please complete the following information):**
-  OS: CentOS 7.9
- `# uname -a`  Linux XXXX 3.10.0-1160.76.1.el7.x86_64 oamg/leapp#1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):
leapp-upgrade-el7toel8-0.16.0-6.el7.elevate.1.noarch
leapp-deps-0.14.0-1.el7.noarch
leapp-0.14.0-1.el7.noarch
leapp-data-rocky-0.1-6.el7.noarch
python2-leapp-0.14.0-1.el7.noarch
leapp-upgrade-el7toel8-deps-0.16.0-6.el7.elevate.1.noarch

****

**Additional context**
Python error:
```
====> * vendor_signed_rpm_scanner
        Provide data about installed RPM Packages signed by Red Hat.
Process Process-290:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 72, in _do_run
    actor_instance.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 290, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/common/actors/redhatsignedrpmscanner/actor.py", line 125, in process
    "Package {} is unsigned, packager: {}, signature: {}".format(pkg.name, pkg.packager, pkg.pgpsig)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 7: ordinal not in range(128)
```

**Comment by pirat89** [comment]
The same issue could happen for the packager field if using nonsense characters here too.
