### ISSUE TITLE
chrony actor traceback due to run(checked= ...)

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp-repository#195]
**Actual behavior**

chrony actor raises traceback due to unknown argument:

    Process Process-120:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 59, in _do_run
        target_actor(logger=logger, messaging=messaging).run(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 299, in run
        self.process(*args)
      File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkchrony/actor.py", line 29, in process
        check_chrony('chrony' in installed_packages)
      File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkchrony/libraries/library.py", line 19, in check_chrony
        if is_config_default():
      File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/checkchrony/libraries/library.py", line 7, in is_config_default
        result = run(['rpm', '-V', '--nomtime', 'chrony'], checked=False)
    TypeError: run() got an unexpected keyword argument 'checked'

**To Reproduce**

1. install leapp
3. run leapp --upgrade

**Expected behavior**

Pre-boot part of the upgrade workflow

**System information (please complete the following information):**

    leapp-0.7.0-1.201904300837Z.f766a84.master.el7_6.noarch
    leapp-repository-0.7.0-1.201905140917Z.24efd84.master.el7_6.noarch

**Comment by mlichvar** [comment]
The chrony actor requires latest leapp from git, which supports the checked parameter in run().

**Comment by AloisMahdal** [comment]
You mean leapp#498?  That's strange, as that should already be present in the master branch.

**Comment by mlichvar** [comment]
It is, but it was added after leapp-0.7.0-1.201904300837, which you have installed.

**Comment by AloisMahdal** [comment]
Yeah, so I'll have to check why we're getting such old build.  Anyway, the issue is invalid.  Thanks.
