### ISSUE TITLE
Do not use efibootmgr when it's not installed (non-uefi)

### ISSUE THREAD

**Issue by fernflower** [oamg/leapp-repository#389]
Otherwise
```
    dracut: ========================================================================
    dracut: *** Creating initramfs image file '/artifacts/initramfs-upgrade.x86_64.img' done ***
    2019-10-30 07:11:47.838 DEBUG    PID: 1132 leapp.workflow.InterimPreparation.initram_disk_generator: External command has finished: ['systemd-nspawn', '--register=no', '--quiet', '-D', u'/var/lib/leapp/el8userspace', '/bin/sh', '-c', 'LEAPP_ADD_DRACUT_MODULES="sys-upgrade-redhat,sys-upgrade" LEAPP_KERNEL_ARCH=x86_64 LEAPP_DRACUT_INSTALL_FILES="" /generate-initram.sh']
    2019-10-30 07:11:47.925 INFO     PID: 29959 leapp.workflow.InterimPreparation: Executing actor add_upgrade_boot_entry
    2019-10-30 07:11:47.954 DEBUG    PID: 7580 leapp.workflow.InterimPreparation.add_upgrade_boot_entry: External command has started: ['/usr/sbin/grubby', '--remove-kernel', '/boot/vmlinuz-upgrade.x86_64']
    2019-10-30 07:11:47.975 DEBUG    PID: 7580 leapp.workflow.InterimPreparation.add_upgrade_boot_entry: External command has finished: ['/usr/sbin/grubby', '--remove-kernel', '/boot/vmlinuz-upgrade.x86_64']
    2019-10-30 07:11:47.977 DEBUG    PID: 7580 leapp.workflow.InterimPreparation.add_upgrade_boot_entry: External command has started: ['/usr/sbin/grubby', '--add-kernel', '/boot/vmlinuz-upgrade.x86_64', '--initrd', '/boot/initramfs-upgrade.x86_64.img', '--title', 'RHEL-Upgrade-Initramfs', '--copy-default', '--make-default', '--args', 'debug enforcing=0 rd.plymouth=0 plymouth.enable=0']
    2019-10-30 07:11:48.31  DEBUG    PID: 7580 leapp.workflow.InterimPreparation.add_upgrade_boot_entry: External command has finished: ['/usr/sbin/grubby', '--add-kernel', '/boot/vmlinuz-upgrade.x86_64', '--initrd', '/boot/initramfs-upgrade.x86_64.img', '--title', 'RHEL-Upgrade-Initramfs', '--copy-default', '--make-default', '--args', 'debug enforcing=0 rd.plymouth=0 plymouth.enable=0']
    2019-10-30 07:11:48.40  INFO     PID: 29959 leapp.workflow.InterimPreparation: Executing actor efi_interim_fix
    2019-10-30 07:11:48.67  DEBUG    PID: 7629 leapp.workflow.InterimPreparation.efi_interim_fix: External command has started: ['/sbin/efibootmgr']
    2019-10-30 07:11:48.78  DEBUG    PID: 7635 leapp.workflow.InterimPreparation.efi_interim_fix: External command has finished: ['/sbin/efibootmgr']
    Process Process-283:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 63, in _do_run
        target_actor(logger=logger, messaging=messaging, config_model=config_model).run(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 320, in run
        self.process(*args)
      File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/efibootorderfix/interim/actor.py", line 17, in process
        efi_reboot_fix.maybe_emit_updated_boot_entry()
      File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/libraries/efi_reboot_fix.py", line 27, in maybe_emit_updated_boot_entry
        efi_info = run(['/sbin/efibootmgr'], checked=False, split=True)
      File "/usr/lib/python2.7/site-packages/leapp/libraries/stdlib/__init__.py", line 177, in run
        result = _call(args, callback_raw=callback_raw, callback_linebuffered=callback_linebuffered, env=env)
      File "/usr/lib/python2.7/site-packages/leapp/libraries/stdlib/call.py", line 218, in _call
        os.execvpe(command[0], command, env=environ)
      File "/usr/lib64/python2.7/os.py", line 353, in execvpe
        _execvpe(file, args, env)
      File "/usr/lib64/python2.7/os.py", line 368, in _execvpe
        func(file, *argrest)
    OSError: [Errno 2] No such file or directory
```

**Comment by pirat89** [comment]
Fixed: #385
